

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install --save-dev jest --force && npm install
    command: npm test ./test/single.test.js
